Repository unosquare/uno-material-ui, pull requests merged in 2019-07, with the labels that each got.

#38 Added context for snackbar notifications
  README.md
  src/SnackbarContextProvider.tsx
  src/index.tsx
Labels: enhancement

#40 Added mobile support
  README.md
  dist/SnackbarContextProvider.js
  dist/index.js
  src/SnackbarContextProvider.tsx
  srcdocs/components/GlobalSnackbar.tsx
  srcdocs/pages/Examples.tsx
Labels: enhancement

#43 NavBar responsive
  srcdocs/components/NavBar.tsx
Labels: enhancement

#44 Move navbar
  src/NavBar.tsx
  srcdocs/components/NavBar.tsx
Labels: enhancement

#45 giving callback for unmount component
  src/ThumbnailPhoto.tsx
Labels: bug, enhancement

#55 Changed Navbar styles to correctly display logo
  dist/NavBar.js
  docs/index.html
  docs/pages.fbdb946c.js
  docs/uno-material-logo-white.2007b8a3.svg
  docs/uno-material-logo.15a5d25a.svg
  package-lock.json
  src/NavBar.tsx
  srcdocs/components/Navigation.tsx
Labels: bug
